GigHub/Controllers/DeanController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GigHub.Core.ViewModel;
using GigHub.Persistence;

namespace GigHub.Controllers
{
    public class DeanController : Controller
    {


        private ApplicationDbContext _context;

        public DeanController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Dean
        public ActionResult Index()
        {
            return View();
        }



        public ActionResult getJson()
        {
            var result = _context.Users.Select(s => new
            {
                name = s.Name,
                id = s.Id
            }).Distinct().ToList();
            

            int conut = 0;
            var list = new List<DeanViewModel>();
            foreach (var item in result)
            {
                conut = _context.Gigs.Where(s => s.ArtistId == item.id).Select(s => s.DateTime).Count();
                list.Add(new DeanViewModel() { name = item.name, count = conut });
            }
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult getJsonforColumns()
        {
            var result = _context.Users.Select(s => new
            {
                name = s.Name,
                id = s.Id

            }).Distinct().ToList();


            var list = new List<DeanViewModel>();
            foreach (var item in result)
            {
                var cateId = _context.Gigs.Where(s => s.ArtistId == item.id).Select(d => d.GenreId).ToList();
                 
                foreach (var category in cateId)
                {
                    var e = _context.Gigs.Where(s => s.ArtistId == item.id && s.GenreId == category).Select(s => new DeanViewModel()
                    {
                        name = _context.Gigs.Where(ss => ss.ArtistId == item.id && ss.GenreId == category).Select(d=>d.Genre.Name).FirstOrDefault(),
                        count = cateId.Count()
                    });

                }
              
                //list.Add(new DeanViewModel()
                //{
                //list = e
                //});
            }
            return Json(list, JsonRequestBehavior.AllowGet);
        }





        public ActionResult test()
        {
            var result = _context.Users.Select(s => new
            {
                name = s.Name,
                id = s.Id
            }).Distinct().ToList();

            var gresult = _context.Genres.Select(s => new
            {
                name = s.Name,
                id = s.Id
            }).Distinct().ToList();

            var list = new List<DeanViewModel>();
            foreach (var item in result)
            {

                list.Add(new DeanViewModel()
                {

                name = _context.Gigs.Where(s => s.ArtistId == item.id).Select(d => d.Genre.Name).FirstOrDefault(),

                    list = _context.Gigs.Where(s => s.ArtistId == item.id).ToList(),


                });
            }
            return Json(list, JsonRequestBehavior.AllowGet);
        }

    }
}

GigHub/Views/Dean/Index.cshtml
@model GigHub.Core.ViewModel.DeanViewModel
@{
    ViewBag.Title = "Index";
}

<h1>Dean DashBoard</h1>




<div class="row">

    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <div id="test" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"><div class="loader"><div class="loader__figure"></div></div></div>
            </div>

        </div>
    </div>



    


    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <div id="column" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"><div class="loader"><div class="loader__figure"></div></div></div>
            </div>

        </div>
    </div>
</div>


@section scripts
{

    <script src="https://code.highcharts.com/highcharts.js"></script>

    <script src="https://code.highcharts.com/modules/exporting.js"></script>

    <script src="https://code.highcharts.com/modules/export-data.js"></script>


    <script>



        $(document).ready(function () {







                $.ajax({
                    url: '@Url.Action("getJson", "Dean")',
                    type: 'Get',
                    success: function (result) {
                    //alert(result.length);
                    drawPieChart(result);

                    },
                    error: function(xhr, ajaxOptions, thrownError) {
                    console.log(xhr.statusText);

                    console.log(thrownError);

                    }

                    });


                    $.ajax({
                    url: '@Url.Action("getJsonforColumns", "Dean")',
                    type: 'Get',
                    success: function (result) {
                    //alert(result.length);
                    DrawChartForArtist(result);

                    },
                    error: function(xhr, ajaxOptions, thrownError) {
                    console.log(xhr.statusText);

                    console.log(thrownError);

                    }

                    });


        });






                    // draw high chart for total revenu per country (pie)

                    function drawPieChart(data) {

                    var result = []; // array for serise


                    for (var i = 0; i < data.length; i++) {

                    result.push({ "name": data[i].name, "y": data[i].count });

                    }

                    Highcharts.chart('test',
                    {

                    chart: {

                    plotBackgroundColor: null,

                    plotBorderWidth: null,

                    plotShadow: false,

                    type: 'pie'

                    },

                    credits: {

                    enabled: false

                    },

                    title: {

                    text: 'Total Event Per Family'

                    },

                    tooltip: {

                    pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'

                    },

                    plotOptions: {

                    pie: {

                    allowPointSelect: true,

                    cursor: 'pointer',

                    dataLabels: {

                    enabled: true,

                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',

                    style: {

                    color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'

                    }

                    }

                    }

                    },

                    series: [

                    {

                    type: 'pie',

                    name: 'Total Event',

                    data: result

                    }

                    ]

                    });



                    }



                    function DrawChartForArtist(data) {
                    var result = []; // array for serise
                    for (var i = 0; i < data.length; i++) {

                        result.push({ "name": data[i].name, "Y": data[i].list });

                    }

                    Highcharts.setOptions({
                    });
                    Highcharts.chart('column',
                    {
                    chart: {
                    type: 'column'
                    },
                    credits: {
                    enabled: false
                    },
                    title: {
                    text: 'Event per category'
                    },
                    subtitle: {
                    text: 'expalin how much event provide by family'
                    },
                    xAxis: {
                    type: 'category',
                    labels: {
                    rotation: -45,
                    style: {
                    fontSize: '12px',
                    fontFamily: 'Verdana, sans-serif'
                    }
                    }

                    },



                    //
                    xAxis: {
                        type: 'category',
                        labels: {
                            rotation: -45,
                            style: {
                                fontSize: '12px',
                                fontFamily: 'Verdana, sans-serif'
                            }
                        }

                    },

                    xAxis: {
                        type: 'category',
                        labels: {
                            rotation: -45,
                            style: {
                                fontSize: '12px',
                                fontFamily: 'Verdana, sans-serif'
                            }
                        }

                    },
                    //
                    yAxis: {
                    min: 0,
                    title: {
                    text: 'Levels'
                    }
                    },
                    legend: {
                    enabled: true
                    },
                    tooltip: {
                    pointFormat: 'percentage for this familt in a specific category: <b>{point.y} </b>'
                    },
                    plotOptions: {
                    column: {
                    stacking: 'normal',
                    dataLabels: {
                    enabled: false,
                    color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white'
                    }
                    }
                    },
                    series: [
                        {
                            name:"Category",
                    data: result
                    ,
                    dataLabels: {
                        enabled: true,
                        rotation: -90,
                        color: '#FFFFFF',
                        align: 'right',
                        format: '{point.y:.1f}', // one decimal
                        y: 10, // 10 pixels down from the top
                        style: {
                            fontSize: '13px',
                            fontFamily: 'Verdana, sans-serif'
                        }
                    }
                    }
                    ]
                    });
                    }





                   











    </script>

    }